# multi-pod-chart/Chart.yaml
apiVersion: v2
name: multi-pod-chart
description: A basic Helm chart to create multiple pods from a list in values
# Type indicates this chart is deployable
type: application

# Version of this chart
version: 0.1.0

# Version of the app being deployed (optional)
# appVersion: "1.0"
