services:
  - name: service-alpha  
    type: ClusterIP      
    port: 8080           
    targetPort: 80       
    selector:
      pod-spec-name: pod-alpha
  
  - name: service-gamma
    type: NodePort
    port: 80
    targetPort: 80
    selector:
      pod-spec-name: pod-gamma
  
  - name: service-all-pods
    type: ClusterIP
    port: 9000
    targetPort: 80
    selector:
      app: multi-pod-chart 
